### ISSUE TITLE
Anonymous feedback from the Anonymous form.

### ISSUE THREAD

**Issue by MrValentine7777** [SimonDarksideJ/MonoGame-Tutorials#25]
<html>
<body>

Please fix the issues on the github page and resolve all open pull requests, thank you. |  
-- | --

<br class="Apple-interchange-newline">
</body>
</html>

## What kinds of things would you like to see demonstrated

**Additional context**

**Comment by SimonDarksideJ** [comment]
Closed as not a tutorial request :D
